-- EARL Supabase Schema
-- Im Supabase Dashboard unter SQL Editor vollständig ausführen.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.teams (
  id text primary key,
  name text not null,
  short_code text not null,
  primary_color text not null default '#ff284c',
  secondary_color text not null default '#ffffff',
  team_principal text not null default 'Noch offen',
  is_available boolean not null default true,
  team_chief_card_url text,
  driver_card_url text,
  updated_at timestamptz not null default now()
);
create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  display_name text not null,
  discord_name text,
  nationality text,
  race_number integer check (race_number between 1 and 999),
  team_id text references public.teams(id) on delete set null,
  role text not null default 'Stammfahrer',
  card_image_url text,
  championship_points integer not null default 0,
  penalty_points integer not null default 0,
  wins integer not null default 0,
  podiums integer not null default 0,
  status text not null default 'accepted' check (status in ('pending','accepted','rejected')),
  updated_at timestamptz not null default now()
);
create table if not exists public.races (
  id bigint generated by default as identity primary key,
  round integer not null,
  name text not null,
  circuit text,
  qualifying_date date,
  qualifying_time time,
  race_date date,
  race_time time,
  status text not null default 'Geplant',
  qualifying_open boolean not null default true,
  race_open boolean not null default true,
  updated_at timestamptz not null default now()
);
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  display_name text not null,
  discord_name text not null,
  nationality text,
  race_number integer check (race_number between 1 and 999),
  platform text,
  requested_team_id text references public.teams(id) on delete set null,
  notes text,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.event_signups (
  id bigint generated by default as identity primary key,
  driver_name text not null,
  discord_name text not null,
  race_id bigint not null references public.races(id) on delete cascade,
  signup_type text not null check (signup_type in ('race','qualifying')),
  qualifying_confirmed boolean not null default false,
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint race_requires_qualifying_confirmation check (signup_type <> 'race' or qualifying_confirmed = true)
);
create table if not exists public.rules (
  id bigint generated by default as identity primary key,
  chapter text not null,
  title text not null,
  content text not null,
  sort_order integer not null default 0,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  page_key text not null,
  content_key text not null,
  value text not null,
  updated_at timestamptz not null default now(),
  unique(page_key, content_key)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id,email) values (new.id,new.email)
  on conflict (id) do update set email=excluded.email;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_earl_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce((select is_admin from public.profiles where id=auth.uid()),false); $$;

alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.drivers enable row level security;
alter table public.races enable row level security;
alter table public.registrations enable row level security;
alter table public.event_signups enable row level security;
alter table public.rules enable row level security;
alter table public.site_content enable row level security;

create policy "Own profile or admin read" on public.profiles for select using (id=auth.uid() or public.is_earl_admin());
create policy "Public teams read" on public.teams for select using (true);
create policy "Public accepted drivers read" on public.drivers for select using (status='accepted' or public.is_earl_admin());
create policy "Public races read" on public.races for select using (true);
create policy "Public rules read" on public.rules for select using (published=true or public.is_earl_admin());
create policy "Public content read" on public.site_content for select using (true);
create policy "Public registration submit" on public.registrations for insert with check (status='pending');
create policy "Public event signup" on public.event_signups for insert with check (status='pending' and (signup_type='qualifying' or qualifying_confirmed=true));

create policy "Admins manage profiles" on public.profiles for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage teams" on public.teams for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage drivers" on public.drivers for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage races" on public.races for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage registrations" on public.registrations for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage event signups" on public.event_signups for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage rules" on public.rules for all using (public.is_earl_admin()) with check (public.is_earl_admin());
create policy "Admins manage content" on public.site_content for all using (public.is_earl_admin()) with check (public.is_earl_admin());

insert into public.teams (id,name,short_code,primary_color,secondary_color,team_chief_card_url,driver_card_url) values
('red-bull','Oracle Red Bull Racing','RBR','#3671c6','#ff1e2d','./assets/team-cards/team-chief/red-bull.jpeg','./assets/team-cards/driver/red-bull-driver-card.png'),
('cadillac','Cadillac Racing','CAD','#c8a45b','#ffffff','./assets/team-cards/team-chief/cadillac.jpeg','./assets/team-cards/driver/cadillac-driver-card.png'),
('aston-martin','Aston Martin','AMR','#006f62','#cedc00','./assets/team-cards/team-chief/aston-martin.jpeg','./assets/team-cards/driver/aston-martin-driver-card.png'),
('williams','Williams Racing','WIL','#00a0de','#ffffff','./assets/team-cards/team-chief/williams.jpeg','./assets/team-cards/driver/williams-driver-card.png'),
('audi','Audi F1 Team','AUD','#e10600','#ffffff','./assets/team-cards/team-chief/audi.jpeg','./assets/team-cards/driver/audi-driver-card.png'),
('haas','Haas F1 Team','HAS','#e6002d','#ffffff','./assets/team-cards/team-chief/haas.jpeg','./assets/team-cards/driver/haas-driver-card.png'),
('mclaren','McLaren','MCL','#ff8700','#ffffff','./assets/team-cards/team-chief/mclaren.jpeg','./assets/team-cards/driver/mclaren-driver-card.png'),
('mercedes','Mercedes-AMG','MER','#00d2be','#c0c0c0','./assets/team-cards/team-chief/mercedes.jpeg','./assets/team-cards/driver/mercedes-driver-card.png'),
('alpine','Alpine','ALP','#2293d1','#ff87bc','./assets/team-cards/team-chief/alpine.jpeg','./assets/team-cards/driver/alpine-driver-card.png'),
('ferrari','Scuderia Ferrari','FER','#dc0000','#ffd700','./assets/team-cards/team-chief/ferrari.jpeg','./assets/team-cards/driver/ferrari-driver-card.png')
on conflict (id) do nothing;

insert into public.rules (chapter,title,content,sort_order) values
('01','Allgemeine Teilnahme','Respektvolles Verhalten ist jederzeit verpflichtend. Entscheidungen der Ligaleitung sind zu befolgen.',1),
('02','Qualifying-Pflicht','Wer sich zu einem Rennen anmeldet, muss am zugehörigen Qualifying teilnehmen. Ausnahmen müssen vorab genehmigt werden.',2),
('03','Fair Racing','Absichtliche Kollisionen, gefährliches Wiederauffahren und unsportliches Verhalten werden sanktioniert.',3);

-- ERST NACHDEM du den Benutzer im Supabase-Dashboard angelegt hast ausführen:
-- update public.profiles set is_admin=true where email='anzgarwolf@gmail.com';
